### ISSUE TITLE
Access his dashboard

### ISSUE THREAD

**Issue by Tris-250** [mh9924/CoWFC#34]
Hello, I do not know how to access my dashboard, can you help me, I do not know if I have to enter a web address to access it, thank you.

**Comment by kyle95wm** [comment]
My install script should tell you how at the end.

**Comment by Tris-250** [comment]
Thank you for the info, but when I enter the link on my browser I receive an error message, can you help me, thank you

I use firefox on ubuntu 16.04

**Comment by kyle95wm** [comment]
I can’t help you if I don’t know what the error is.

**Comment by Tris-250** [comment]
The connection failed

Firefox can not connect to the server at 91.164.xx.xxx.

     The site may be temporarily unavailable or overloaded. Try again later;
     If you can not navigate on any site, check the network connection of your computer;
     If your computer or network is protected by a firewall or proxy, make sure Firefox is allowed to access the Web.

**Comment by kyle95wm** [comment]
Which version of Ubuntu are you using? Did you use my installer script?

**Comment by Tris-250** [comment]
I use ubuntu 16.04 and I use the script "mkdir / var / www; cd / var / www && wget https://raw.githubusercontent.com/kyle95wm/cowfc_installer/master/cowfc.sh && chmod + x cowfc .sh && ./cowfc.sh "and after (rebooting) I use" cd / var / www / && ./cowfc.sh "

**Comment by kyle95wm** [comment]
Okay. I’ll try building a new system today on 16.04. Maybe something came un-glued.

**Comment by Tris-250** [comment]
Ok thank you

**Comment by kyle95wm** [comment]
Just built a new Ubuntu 16.04 instance on Vultr using [this](https://github.com/kyle95wm/CoWFC) and was able to access the dash and log in without issue.

**Comment by Tris-250** [comment]
I did not install CoWFC on Vultr, could the problem come from there ?

thank you

**Comment by kyle95wm** [comment]
Not sure. Who is your cloud hosting provider? If you're using OpenVZ containers, it mght be a problem. Getting CoWFC running on OpenVZ was a pain for me and wasn't worth it in the end.

**Comment by Tris-250** [comment]
I do not use a host, wanting to create a private server, I use a simple computer, the problem is there from there?

thank you so much

**Comment by Tris-250** [comment]
for the http i'm using apache

**Comment by kyle95wm** [comment]
Okay, since you're self-hosting this server, did you make sure that you port-forwarded the appropriate ports to allow connections? The AltWFC wiki's troubleshooting page has all the port numbers you need to forward. This includes opening port 80 for web access.

This might be why you're getting a "connection failed" error. Since this computer is on your LAN, try accessing the admin GUI via its PRIVATE IP (not the 91.xx.xx.xx IP)

**Comment by Tris-250** [comment]
ok I will try, thank you very much

**Comment by kyle95wm** [comment]
No problem!

**Comment by Tris-250** [comment]
Hello, I managed to access the control panel, thank you very much, but I do not know what I have to enter the DSN on my Nintendo DS, can you help me, thank you very much

**Comment by kyle95wm** [comment]
Okay, so this immediatly tells me that you didn't port-forward anything, which will mean that using your public IP for DNS won't work.


To fix this for internal testing, edit the file `/etc/dnsmasq.conf` and scroll to the bottom, changing anything with your public IP in it, with your private IP instead. Then run ```sudo service dnsmasq restart```

On your console, set the DNS to the private IP.  From this point onward, everything should work as you expect it to. In order to get outside access, you'll need to port forward on your router to your host. Please look [here](https://github.com/barronwaffles/dwc_network_server_emulator/wiki/Troubleshooting#port-forwarding) for information on how to do that.

**Comment by kyle95wm** [comment]
Once you're ready to publish your server to the world, don't forget to change your dnsmasq config back to a public IP or it won't work. Internally, you'll need to use the public IP on your consoles as well.

**Comment by Tris-250** [comment]
I can not restart dnsmasq I get the error

Job for dnsmasq.service failed because the control process is exited with error code. See "systemctl status dnsmasq.service" and "journalctl -xe" for details.

Can you help me ?

**Comment by kyle95wm** [comment]
Can you show the bottom part of your dnsmasq config where it shows things like nintendowifi and wiimmfi? I suspect your config file is botched somewhere.

**Comment by Tris-250** [comment]
# For debugging purposes, log each DNS query as it passes through
# dnsmasq.
#log-queries

# Log lots of extra information about DHCP transactions.
#log-dhcp

# Include another lot of configuration options.
#conf-file=/etc/dnsmasq.more.conf
#conf-dir=/etc/dnsmasq.d

# Include all the files in a directory except those ending in .bak
#conf-dir=/etc/dnsmasq.d,.bak

# Include all files in a directory which end in .conf
#conf-dir=/etc/dnsmasq.d/,*.conf
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"
server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"

**Comment by kyle95wm** [comment]
Woah!

There should only be one instance of 

```server=8.8.8.8
address=/nintendowifi.net/192.168.0.22
address=/wiimmfi.de/192.168.0.22
interface="eth0"```


So get rid of the rest of those and try restarting dnsmasq. How did you get so many of those? The installer shouldn't be duplicating so many.

**Comment by Tris-250** [comment]
hello, I delete the code too much but I always make a mistake, so I run : systemctl status dnsmasq.service and I received the error :

Active: failed (Result: exit-code) since mer. 2019-03-27 20:12:28 CET; 10s ago
  Process: 4650 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
and mars 27 20:12:28 pc-linux systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.

I also run journalctl-xe: - The unit (unit) dnsmasq.service started to start.
March 27 20:17:11 pc-linux dnsmasq [4835]: dnsmasq: OK syntax check.
Mar 27 20:17:11 pc-linux dnsmasq [4839]: dnsmasq: unknown eth1 interface
March 27 20:17:11 pc-linux dnsmasq [4839]: unknown eth0 interface
March 27 20:17:11 pc-linux dnsmasq [4839]: IMPOSSIBLE to start
Mar 27 20:17:11 pc-linux systemd [1]: dnsmasq.service: control process exited, c
March 27 20:17:11 pc-linux systemd [1]: Failed to start dnsmasq - A lightweight DH
- Subject: The unit (unit) dnsmasq.service failed
- Defined-By: systemd
- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-
- The unit (unit) dnsmasq.service failed, with the result failed.
Mar 27 20:17:11 pc-linux systemd [1]: Dependency failed for Host and Network Nam
- Subject: The unit (unit) nss-lookup.target failed
- Defined-By: systemd
- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-
- The unit (unit) nss-lookup.target failed, with the result dependency.
Mar 27 20:17:11 pc-linux systemd [1]: nss-lookup.target: Job nss-lookup.target/s
Mar 27 20:17:11 pc-linux systemd [1]: dnsmasq.service: Unit entered failed state
Mar 27 20:17:11 pc-linux systemd [1]: dnsmasq.service: Failed with result 'exit-
March 27 20:17:11 pc-linux sudo [4829]: pam_unix (sudo: session): session closed for

do you know where the error comes from ?, thank you very much

**Comment by kyle95wm** [comment]
Check to make sure you have the proper listening interface configured. I saw an error in there that said something about eth1. Make sure the listening interface matches what ifconfig gives you.

**Comment by Tris-250** [comment]
Hello, I do not know what is the listening interface, can you help me please
I reinstall CoWFC and I have no more error for the command "daylalctl -xe" but I always get the error "dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset:
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq- $ named.conf, 50-insserv.conf- $ named.conf
   Active: failed (Result: exit-code) since Thu 2019-03-28 20:06:08 CET; 9min to
  Process: 2670 ExecStart = /etc/init.d/dnsmasq systemd-exec (code = exited, status =
  Process: 2667 ExecStartPre = / usr / sbin / dnsmasq --test (code = exited, status = 0 / SUC

March 28 20:06:08 pc-linux systemd [1]: Starting dnsmasq - A lightweight DHCP
March 28 20:06:08 pc-linux dnsmasq [2667]: dnsmasq: OK syntax check.
Mar 28 20:06:08 pc-linux dnsmasq [2670]: dnsmasq: unknown eth0 interface
March 28 20:06:08 pc-linux systemd [1]: dnsmasq.service: control process exited, c
March 28 20:06:08 pc-linux systemd [1]: Failed to start dnsmasq - A lightweight DH
Mar 28 20:06:08 pc-linux systemd [1]: dnsmasq.service: The unit entered failed state
Mar 28 20:06:08 pc-linux systemd [1]: dnsmasq.service: Failed with result 'exit- "for the command" systemctl status dnsmasq.service "

Do you have an idea of where the error may come from ? Thank you

**Comment by kyle95wm** [comment]
To find out what interface you should be listening on, run “ifconfig” and find the name of the interface that has your local IP with it. I believe some new versions of Ubuntu call it “ens3” instead of “eth0” or something like that.

**Comment by Tris-250** [comment]
Hello, thank you very much for your help, my listening interface was very invalid, I managed to do my tests internally (but I do not know the code to add games to my whitelist) but I know it works , but I do not know what redirection I have to do to use my server without being connected to the same network, can you help me, thank you very much

**Comment by kyle95wm** [comment]
To add games to the whitelist, log into the CoWFC admin panel and go to the whitelist page. Add the game's first 3 letters of the ID. For example to whitelist Mario Kart Wii, type RMC, instead of typing RMCE

Doing it this way will cover all regions for a game. To make your server accessible from outside your network, go and look at [this](https://github.com/barronwaffles/dwc_network_server_emulator/wiki/Troubleshooting#port-forwarding) and forward the needed ports to your server. The alternative to port forwarding is using something on your router called DMZ, which exposes one computer to the internet on all TCP and UDP ports.

If you're going to expose your server to the internet, I would remove the `server=8.8.8.8` line from your dnsmasq config file. If you don't do this, you're creating an open resolver, which in itself is [a very bad idea](https://simpledns.com/kb/155/what-is-an-open-dns-server-and-how-do-i-fix-it)

Hope this helps.

Edit: the new installers now exclude the `server=8.8.8.8` line from the dnsmasq config, so if you ever plan on re-building your system, just know you don't have to worry about that.

**Comment by Tris-250** [comment]
hello, I managed to add mario kart ds in the admin page CoWFC, but I have not managed to make my server accesible from another network, I put my external ip in dnsmasq and delete "server = 8.8.8.8 "(which I do not even know what it was for), enable DMZ and redirect the traffic to my computer but I can not connect, I put my external IP address on the nitendo ds , do you know where the problem may come from, thank you very much for your help

**Comment by kyle95wm** [comment]
Did you make sure to update your dnsmasq config to update the IP addresses?

Can you access your server's website via its external IP?

**Comment by Tris-250** [comment]
Hello, I manage to access the web page with the address 91.xx.xx.xx but not from another network, I re installed CoWFC and check my configuration dnsmasq, I can connect to the internet with my nintendo ds (from another network) but when I go in CWF Nintendo game I receive the error 20100, I specify that I have patched the game (I had managed to connect to local) and properly configure the dsn on 91.xx.xx.xx but I still get the error, could it come from the DMZ, (but I have it enabled and configured to redirect the traffic to my computer)

Thank you very much for your help

**Comment by kyle95wm** [comment]
By "your computer" are you referring to your server?

**Comment by Tris-250** [comment]
Hello, I have reinstalled Ubuntu 16.04 on my computer (to delete duplicate files that could have slipped during my reinstallation) and install CoWFC, I put the dnsmasq configuration on my external ip address and check if DMZ was to activate well, I also check if my games were well patched, I after retry but I received "Error 52100" can not connect to the server, by "my computer" I mean my server.

thanks a lot for your help

**Comment by kyle95wm** [comment]
Hm, I'm not really sure what's causing the issue. Does your external IP work if you enter it into a web browser to access your server's website?

**Comment by Tris-250** [comment]
Hello I can enter my internal and external ip address on mob server

**Comment by Tris-250** [comment]
Hello, I tested ping from my local network and from another network, on my local network I manage to access the address 91.xx.xx.xx but not from another network, which explains why I can not connect my Nintend ds from another network.

I do not understand, I have defined dnsmasq on 91.xx.xx.xx and configure DMZ

Do you know where the problem may come from, thank you very much

**Comment by kyle95wm** [comment]
No, sadly I don't. Your router might be blocking the connection for some reason.

**Comment by Tris-250** [comment]
hello, after knowing I found that my ISP had blocked the ports below 16384, (probably for security) which explains the problem.

If I ask for a V4 full-stack fixed IP address, it may cause me problems with security, or internet connection

Also does CoWFC support gallery flipnote studio dsi

**Comment by Tris-250** [comment]
Thank you very much

**Comment by kyle95wm** [comment]
I don't know what games are supported by CoWFC or its prior forks. ANY game can be enabled through the whitelist, but beyond that, there are no guarantees.

**Comment by Tris-250** [comment]
Hello, thank you for your help, I reinstall Ubuntu, then CoWFC, I have installed all the components that had to install before installing CoWFC, I configure the port of my Internet box, my computer with Gufw Firewall, the game of my Nintendo DS is well patched (I was able to connect to another server).

And I can access the home web page from another network, but I can not connect my Nintendo DS to my server, I get error 52100, can you help me

I'm using Ubuntu 16.04, can this come from the security update

**Comment by Tris-250** [comment]
Thank you very much

**Comment by Tris-250** [comment]
Hello, I managed to connect to my server CoWFC, it was a problem related to the firewall

thanks a lot for your help
