### ISSUE TITLE
Missing Web files & Folders

### ISSUE THREAD

**Issue by kyle95wm** [mh9924/CoWFC#7]
There are critical files missing from the Web folder that make the website look the way it should. I did a compare, and you're missing .htaccess, css and a few other files and directories. Was this intentional?

**Comment by mh9924** [comment]
The prerequisites for installing the repo are the HTML5 templates (Landed and SBAdmin) which include these folders. I did not include them as they have their own license, and the website could still be modified to use other templates. An Apache .htaccess file is not relevant to the source and would depend on the needs of the developer's web server.
